version: '2.6'
services:
  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?connectTimeout=3000&socketTimeout=3000
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_URL=redis://redisson:6379
    depends_on:
      - mysql
      - redisson
    mem_limit: 1G
    cpus: 2.0
    volumes:
      - ./logs/app.log:/app/logs/app.log

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "8888:3306"
    mem_limit: 1G
    cpus: 2.0

  redisson:
    image: redis:7
    ports:
      - "9999:6379"
    mem_limit: 512M
    cpus: 1.0