spring:
  profiles:
    include: secret
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
      leak-detection-threshold: 2000
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: false
      resolve-lazily: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  tomcat:
    threads:
      min-spare: 50
      max: 200
    accept-count: 100
    max-connections: 200
    connection-timeout: 5000


share:
  server-domain: localhost:8080

logging:
  level:
    root: info
    com.zaxxer.hikari: error
