[agent]
  hostname = "test-server2"
  interval = "2s"           # 10초마다 메트릭 수집
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"     # 10초마다 InfluxDB에 전송
  flush_jitter = "0s"
  precision = "1s"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://host.docker.internal:8086"]
  token = "mPEXNne_-p2R2_lfUWwFQLLub01r2lzr8E0SwQN8S2QHx8X96kAHNfFEOtq-hRKoKmG_YFpyKz1hFRG09W6C1Q=="
  organization = "seungh"
  bucket = "test"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fieldexclude = ["time_*"]

[[inputs.mem]]


[[inputs.net]]
  interfaces = ["eth0"]

